apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: eshop
  name: eshop
  namespace: github
spec:
  replicas: 2
  selector:
    matchLabels:
      app: eshop
  strategy: {}
  template:
    metadata:
      labels:
        app: eshop
    spec:
      containers:
      - image: lfraileacr.azurecr.io/eshop-web:#{TAG}#
        env:
        - name: ConnectionStrings__CatalogConnection
          valueFrom:
            secretKeyRef:
              name: conn-strings
              key: catalog-connstring
        - name: ConnectionStrings__IdentityConnection
          valueFrom:
            secretKeyRef:
              name: conn-strings
              key: identity-connstring
        name: eshop-web
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
---
apiVersion: v1
kind: Service
metadata:
  name: eshop-svc
  namespace: github
spec:
  type: ClusterIP  
  selector:
    app: eshop
  ports:
  - protocol: TCP
    name: eshop
    port: 80
    targetPort: 80
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: eshop-ing
  namespace: github
  annotations:
    kubernetes.io/ingress.class: addon-http-application-routing
    ingress.kubernetes.io/ssl-redirect: "false"    
    nginx.ingress.kubernetes.io/force-ssl-redirect: "false"    
spec:
  rules:
  - host: eshop.f1be470dbb8141be8144.westeurope.aksapp.io
    http:
      paths:
      - path: /
        backend:
          serviceName: eshop-svc
          servicePort: 80