apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: eshop
  name: eshop
  namespace: github
spec:
  containers:
  - image: lfraileacr.azurecr.io/heroesapi:20210128.1
    name: eshop
    ports:
    - containerPort: 80
    resources: {}
  restartPolicy: Always
status: {}