apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    app: eshop
  name: eshop
  namespace: github
spec:
  containers:  
  - image: lfraileacr.azurecr.io/eshop-web:#{TAG}#
    env:
      - name: ConnectionStrings__CatalogConnection
        valueFrom:
          secretKeyRef:
            name: conn-strings
            key: catalog-connstring
      - name: ConnectionStrings__IdentityConnection
        valueFrom:
          secretKeyRef:
            name: conn-strings
            key: identity-connstring
    name: eshop
    ports:
    - containerPort: 80
    resources: {}
  restartPolicy: Always
status: {}
---
apiVersion: v1
kind: Service
metadata:
  name: eshop-svc
  namespace: github
spec:
  type: LoadBalancer  
  selector:
    app: eshop
  ports:
  - protocol: TCP
    name: eshop
    port: 80
    targetPort: 80