version: '3.4'

services:
  eshopwebrazor:
    image: eshopwebrazor-latest
    build:
      context: .
      dockerfile: src/WebRazorPages/Dockerfile
    networks:
     - eshop-network
    depends_on:
     - sql-db

  eshopwebmvc:
    image: eshopwebmvc-latest
    build:
      context: .
      dockerfile: src/Web/Dockerfile
    networks:
     - eshop-network
    depends_on:
     - sql-db
  
  sql-db:
    image: microsoft/mssql-server-linux:2017-latest
    networks:
     - eshop-network

networks:
 eshop-network:
  driver: bridge