version: '3'

services:
  eshopwebrazor:
    image: eshopwebrazor
    build:
      context: .
      dockerfile: src/WebRazorPages/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://*:5107;http://0.0.0.0:5107
      - ConnectionStrings:CatalogConnection=Server=sql-db;Database=Microsoft.eShopOnWeb.CatalogDb;User Id=sa;Password=Pass@word
      - ConnectionStrings:IdentityConnection=Server=sql-db;Database=Microsoft.eShopOnWeb.Identity;User Id=sa;Password=Pass@word
      - UseDb=true
    ports:
      - "5107:5107"

  eshopwebmvc:
    image: eshopwebmvc
    build:
      context: .
      dockerfile: src/Web/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://*:5106;http://0.0.0.0:5106
      - ConnectionStrings:CatalogConnection=Server=sql-db;Database=Microsoft.eShopOnWeb.CatalogDb;User Id=sa;Password=Pass@word
      - ConnectionStrings:IdentityConnection=Server=sql-db;Database=Microsoft.eShopOnWeb.Identity;User Id=sa;Password=Pass@word
      - UseDb=true
    ports:
      - "5106:5106"
  
  sql-db:
    image: microsoft/mssql-server-linux:2017-latest
    ports:
     - "5453:1433"
    environment:
     - SA_PASSWORD=Pass@word
     - ACCEPT_EULA=Y

# networks:
#   default:
#     external:
#       name: nat