name: Docker Build and Push

on:
# TODO: add additional triggers
  workflow_dispatch:

env:
  REGISTRY: ghcr.io

jobs:
  docker:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image:
          - Web
          - PublicApi
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    # TODO: change auth to use GitHub app instead of PAT
    - name: Login to ${{ env.REGISTRY }}
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.RPOC_PAT }}

    - name: Convert image name to lowercase
      run: echo "IMAGE_NAME=$(echo "${{ github.repository }}/${{ matrix.image }}" | awk '{print tolower($0)}')" >> $GITHUB_ENV

    # TODO: add docker/metadata-action to apply tags based on branch, env, etc.
    # TODO: consider project structure, where dockerfile might be, how devs might provide manifests, etc.
    - name: Build Docker image for Web
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./src/${{ matrix.image }}/Dockerfile
        push: false
        tags: ghcr.io/${{ env.IMAGE_NAME }}:latest
        labels: |
          org.opencontainers.image.source=https://github.com/${{ github.repository }}

    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: 'image'
        scanners: 'vuln,secret'
        image-ref: 'docker.io/${{ env.IMAGE_NAME }}:latest'
        format: 'table'
        exit-code: '1'
        ignore-unfixed: true
        vuln-type: 'os,library'
        severity: 'CRITICAL,HIGH'