name: Docker CI 

on:
  push:
    branches:
      - master
    tags:
      - dev*

env:
  IMAGE_NAME: eShop

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run tests
        run: |
          if [ -f docker-compose.test.yml ]; then
            docker-compose --file docker-compose.test.yml build
            docker-compose --file docker-compose.test.yml run sut
          else
            echo "No Implemented docker-compose test"
          fi

  build up:
    needs: test

    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - uses: actions/checkout@v2

      - name: Build the stack
        run: docker-compose up -d
