name: Docker Build and Push

on:
  workflow_dispatch:

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.RPOC_PAT }}

    - name: Build and push Docker image for Web
      uses: docker/build-push-action@v5
      with:
        context: ./src/Web
        file: ./src/Web/Dockerfile
        push: true
        tags: ghcr.io/${{ github.repository }}/web:latest

    - name: Build and push Docker image for PublicApi
      uses: docker/build-push-action@v5
      with:
        context: ./src/PublicApi
        file: ./src/PublicApi/Dockerfile
        push: true
        tags: ghcr.io/${{ github.repository }}/publicapi:latest