# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Web 1 - Build and deploy container app to Azure Web App

on: [workflow_dispatch]

jobs:
  build:
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to registry
        uses: docker/login-action@v2
        with:
          registry: https://cloudxcontainerregistry.azurecr.io/
          username: ${{ secrets.AzureAppService_ContainerUsername_3988dc814efa4afca0fe8a442c08144d }}
          password: ${{ secrets.AzureAppService_ContainerPassword_50e6c57b56f642ac8da83a3429a4300b }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: cloudxcontainerregistry.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_3988dc814efa4afca0fe8a442c08144d }}/eshopwebmvc:${{ github.sha }}
          file: ./src/Web/Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: "production"
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: "eshopwebmvc"
          slot-name: "production"
          publish-profile: ${{ secrets.AzureAppService_PublishProfile_a812fbd8674a4d769f8c320c0a65388a }}
          images: "cloudxcontainerregistry.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_3988dc814efa4afca0fe8a442c08144d }}/eshopwebmvc:${{ github.sha }}"
