name: Promote

on:
  push:
    branches: aks
    paths: 
      - .github/workflows/promote.yml
  workflow_dispatch:
    inputs:
      tag_to_promote:
        description: 'Tag to promote'
        required: true
        default: '27b39c05cd5a93be00bc5811d636d932cacda36fd53d1bb6aa82b7a7427227d9'

env:
  build_config: Release      
  registry_name: lfraileacr.azurecr.io
  repository_name: eshop-web
  tag: '27b39c05cd5a93be00bc5811d636d932cacda36fd53d1bb6aa82b7a7427227d9'
  NAMESPACE: github
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Find and Replace tag
      run: find *.yml -type f -exec sed -i ''s/#{TAG}#/${{ env.tag }}/g'' {} \;
      working-directory: aks

    - uses: azure/k8s-set-context@v1
      with:
        method: kubeconfig
        kubeconfig: ${{ secrets.AKS_KUBECONFIG }}
        context: lfraileaks
      id: setcontext
      
    - uses: Azure/k8s-create-secret@v1
      with:        
        namespace: ${{ env.NAMESPACE }}
        container-registry-url: ${{ env.registry_name }}
        container-registry-username: ${{ secrets.ACR_USER_NAME }}
        container-registry-password: ${{ secrets.ACR_PASSWORD }}
        secret-name: secret-github-acr

    - uses: azure/k8s-deploy@v1    
      with:
        manifests: |
          aks/eshop.yml
        images: |
          ${{ env.registry_name }}/${{ env.repository_name }}:${{ env.tag }}
        imagepullsecrets: |
          secret-github-acr
        namespace: ${{ env.NAMESPACE }}
        action: promote
